// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $electrician_2_layout from "./routes/electrician-2/_layout.tsx";
import * as $electrician_2_examday_index from "./routes/electrician-2/examday/index.tsx";
import * as $electrician_2_fukusenzu_examno_ from "./routes/electrician-2/fukusenzu/[examno].tsx";
import * as $electrician_2_fukusenzu_index from "./routes/electrician-2/fukusenzu/index.tsx";
import * as $electrician_2_index from "./routes/electrician-2/index.tsx";
import * as $electrician_2_practicalexam_index from "./routes/electrician-2/practicalexam/index.tsx";
import * as $electrician_2_vvfstripper_index from "./routes/electrician-2/vvfstripper/index.tsx";
import * as $electrician_2_vvrcable_index from "./routes/electrician-2/vvrcable/index.tsx";
import * as $electrician_2_writtenexam_index from "./routes/electrician-2/writtenexam/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $fukusenzu_FukusenzuApp from "./islands/fukusenzu/FukusenzuApp.tsx";
import * as $fukusenzu_Mondai_1 from "./islands/fukusenzu/Mondai_1.tsx";
import * as $fukusenzu_Mondai_2 from "./islands/fukusenzu/Mondai_2.tsx";
import * as $fukusenzu_Mondai_3 from "./islands/fukusenzu/Mondai_3.tsx";
import * as $fukusenzu_class from "./islands/fukusenzu/class.js";
import * as $fukusenzu_data from "./islands/fukusenzu/data.js";
import * as $fukusenzu_functions from "./islands/fukusenzu/functions.js";
import * as $fukusenzu_sprite from "./islands/fukusenzu/sprite.js";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/electrician-2/_layout.tsx": $electrician_2_layout,
    "./routes/electrician-2/examday/index.tsx": $electrician_2_examday_index,
    "./routes/electrician-2/fukusenzu/[examno].tsx":
      $electrician_2_fukusenzu_examno_,
    "./routes/electrician-2/fukusenzu/index.tsx":
      $electrician_2_fukusenzu_index,
    "./routes/electrician-2/index.tsx": $electrician_2_index,
    "./routes/electrician-2/practicalexam/index.tsx":
      $electrician_2_practicalexam_index,
    "./routes/electrician-2/vvfstripper/index.tsx":
      $electrician_2_vvfstripper_index,
    "./routes/electrician-2/vvrcable/index.tsx": $electrician_2_vvrcable_index,
    "./routes/electrician-2/writtenexam/index.tsx":
      $electrician_2_writtenexam_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/fukusenzu/FukusenzuApp.tsx": $fukusenzu_FukusenzuApp,
    "./islands/fukusenzu/Mondai_1.tsx": $fukusenzu_Mondai_1,
    "./islands/fukusenzu/Mondai_2.tsx": $fukusenzu_Mondai_2,
    "./islands/fukusenzu/Mondai_3.tsx": $fukusenzu_Mondai_3,
    "./islands/fukusenzu/class.js": $fukusenzu_class,
    "./islands/fukusenzu/data.js": $fukusenzu_data,
    "./islands/fukusenzu/functions.js": $fukusenzu_functions,
    "./islands/fukusenzu/sprite.js": $fukusenzu_sprite,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
